import { HorizontalBox, Button, ListView, VerticalBox, StandardTableView, ScrollView } from "std-widgets.slint";
import { SlintTrack, SlintQueueItem, MediaActions, SlintPlaylist, MainView } from "../data-flow.slint";
import { Palette } from "../style.slint";
import { TrackContextMenu } from "../components/track-context-menu.slint";
import { Filler } from "../custom-elements/filler.slint";

export component MainList {
	in property<[SlintTrack]> list;
	in property<[SlintPlaylist]> playlists;
	property<MainView> main-view-id: MainView.index;

	ScrollView {
		height: parent.height + 50px;

		VerticalLayout {
			spacing: 5px;
			alignment: start;

			for media in list: TouchArea {
				clicked => {
					MediaActions.add_to_queue(media.id);
					MediaActions.media_start(media.id);
				}

				Rectangle {
					background: Palette.secondary-background;

					HorizontalLayout {
						spacing: 25px;

						VerticalBox {
							Text { text: media.title; }
							Text {
								font-size: 10px;
								text: media.artist;
							}
						}
						Filler {}
						HorizontalBox {
							width: 60px;
							vertical-stretch: 1;
							alignment: center;
							spacing: 5px;

							Text {
								font-size: 10px;
								vertical-alignment: center;
								text: media.str_duration;
							}
							Text {
								vertical-alignment: center;
								text: media.playing ? "Playing" : "";
							}
						}
					}
				}

				TrackContextMenu {
					track: media;
				}
			}
		}
	}
}
