export component IconButton inherits Rectangle {
    in property <string> text;
    in property <int> font-size: 18;
    in property <TextHorizontalAlignment> h-alignment: center;
    callback clicked <=> touch.clicked;

    background: touch.pressed ? #00000022 : (touch.has-hover ? #00000011 : transparent);
    border-radius: 20px;
    height: 30px;
    width: 30px;

    Text {
    	width: 100%;
    	font-size: font-size * 1px;
        horizontal-alignment: h-alignment;
        vertical-alignment: center;
        text: root.text;
    }

    touch := TouchArea {
    	width: 100%;
    }
}
