import {
    SlintState,
    SettingActions,
    MediaActions,
    ContextMenuActions,
    SearchActions,
} from "data-flow.slint";
import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Queue } from "queue.slint";
import { SideBar } from "side-bar.slint";
import { MainList } from "./screens/main-list.slint";
import { MediaControllers } from "media-controllers.slint";
import { MobileQueue } from "mobile-queue.slint";
import { DisplayBox } from "components/display-box.slint";
import { Search } from "components/search.slint";
import { IconButton } from "custom-elements/custom-button.slint";
export { SlintState, SettingActions, SearchActions, MediaActions, ContextMenuActions }

component Container inherits Rectangle {
    in property <string> label: "Container";

    background: pink;
    border-color: black;
    border-radius: 4px;
    border-width: 1px;
    min-height: 80px;

    VerticalLayout {
        padding: 8px;
        spacing: 4px;

        Text {
            text: "";
            horizontal-alignment: center;
            font-weight: 700;
        }
    }
}

export component AppWindow inherits Window {
	preferred-width: 900px;
	preferred-height: 1000px;
	min-width: 400px;
    title: "EMPlayer";

    property <length> sidebar-width: 200px;
    property <length> queue-width: 200px;
    property <length> breakpoint: 600px;
    property <bool> is-small: root.width < breakpoint;

    top_container := Container {
      	z: 10;
    	y: 0;
    	height: 50px;
     	width: 100%;

      	HorizontalBox {
       		Text { text: "Test text"; }
      		search := Search { horizontal-stretch: 1; }
	        IconButton {
				text: "";
				clicked => { SettingActions.new_local_source() }
			}
        	Text { text: "Test text"; }
        }
    }

    // Wide layout
	if !is-small: HorizontalLayout {
		y: top_container.height;
        spacing: 0px; // 12px
		// vertical-stretch: 90;

		sidebar := Container {
            height: parent.height - controllers.height - 10px - top_container.height;
			// horizontal-stretch: 15;
			width: root.sidebar-width;

			SideBar {
				width: parent.width - 10px;
				height: parent.height;
                list: SlintState.playlist;
            }
        }

        Rectangle {
            width: 10px;
            height: parent.height - controllers.height - 10px - top_container.height;
            background: sidebar_handle.pressed ? #6688cc : transparent;

            sidebar_handle := TouchArea {
                mouse-cursor: ew-resize;
                property <length> press-abs-x: 0px;
                property <length> press-width: 0px;

                pointer-event(event) => {
                    if (event.kind == PointerEventKind.down) {
                        self.press-abs-x = self.absolute-position.x + self.mouse-x;
                        self.press-width = root.sidebar-width;
                    }
                }

                moved => {
                    if (self.pressed) {
                        root.sidebar-width += (self.absolute-position.x + self.mouse-x) - self.press-abs-x;
                    }
                }
            }
        }

        main_container := Container {
            height: parent.height - controllers.height - 10px - top_container.height;
            horizontal-stretch: 1;

            MainList {
				y: parent.y + 30px;
				width: parent.width - 10px;
				height: parent.height - 55px;
				list: SlintState.index;
            }
        }

        Rectangle {
            width: 10px;
            height: parent.height - controllers.height - 10px - top_container.height;
            background: queue-handle.pressed ? #6688cc : transparent;

            queue-handle := TouchArea {
                mouse-cursor: ew-resize;

                property <length> press-abs-x: 0px;
                property <length> press-width: 0px;

                pointer-event(event) => {
                    if (event.kind == PointerEventKind.down) {
                        self.press-abs-x = self.absolute-position.x + self.mouse-x;
                        self.press-width = root.queue-width;
                    }
                }

                moved => {
                    if (self.pressed) {
                        root.queue-width += (self.absolute-position.x + self.mouse-x) - self.press-abs-x;
                    }
                }
            }
        }

        queue := Container {
            height: parent.height - controllers.height - 10px - top_container.height;
            width: SlintState.queue.length > 0 ? root.queue-width : 0;
			// horizontal-stretch: 15;

			Queue {
				width: parent.width - 10px;
				height: parent.height - 55px;
				queue: SlintState.queue;
				// min-width: parent.width * 0.1;
				// horizontal-stretch: 1;
			}
        }
    }

    // Layout after the breakpoint
	if is-small: VerticalLayout {
        // spacing: 12px;
		// vertical-stretch: 90;

		main_elements := HorizontalLayout {
            Container {
                horizontal-stretch: 30;
                vertical-stretch: 80;

                SideBar {
					width: parent.width - 10px;
					height: parent.height - 55px;
                 	list: SlintState.playlist;
                }
            }

            Container {
                horizontal-stretch: 70;
                vertical-stretch: 80;

                MainList {
					// min-width: parent.width * 0.6;
					// horizontal-stretch: 1;
					width: parent.width;
					height: parent.height;
					list: SlintState.index;
                }
            }
        }

        Container {
            horizontal-stretch: 1;
			// vertical-stretch: 10;

			Queue {
				width: parent.width - 10px;
				height: parent.height - 55px;
				queue: SlintState.queue;
				// min-width: parent.width * 0.1;
				// horizontal-stretch: 1;
			}
        }
    }

    controllers := Container {
        y: parent.height - self.height;
        height: 80px;
        width: 100%;

		MediaControllers {
			height: 100%;
			width: 100%;
			playing: SlintState.timeline;
		}
    }
}
