import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { Queue } from "queue.slint";
import { SideBar } from "side-bar.slint";
import { MainList } from "main-list.slint";
import { MediaControllers } from "media-controllers.slint";
import { SlintState, SettingActions, MediaActions } from "data-flow.slint";

export { SlintState, SettingActions, MediaActions }

export component AppWindow inherits Window {
	preferred-width: 100%;
    preferred-height: 100%;

	property<physical-length> gl-margin: 5px;
	property<physical-length> gl-padding: 5px;

    main-view := HorizontalBox {
		x: 0px;
		y: 0px;
		width: 100%;

		if root.width > 500px:
			SideBar { playlists: []; y: 0; }

		MainList {
			min-width: root.width * 60%;
			height: root.height - 150px;
			
			list: SlintState.index;
		}

		if root.width > 700px:
			Queue { y: 0; }
	}

	vertical-view := VerticalBox {
		x: 0px;
		y: parent.height - self.height;
		height: 150px;

		Button {
			text: "test";
			clicked => { SettingActions.new_local_source() }
		}

		if root.width < 500px:
			SideBar { }

		if root.width < 700px:
			Queue { }

		MediaControllers {}
	}
}
