export struct SlintTrack {
	id: int,
	name: string,
	artists: string,
	path: string,
	extension: string,
	file_size: int,
	duration: int,
	playing: bool,
}

export struct SlintQueueItem {
	media_id: int,
}

export struct SlintTimeLine {
	current: int,
	length: int
}

export struct SlintSettings {
	volume_preset: int,
}

export struct SlintPlaylist {
	id: int,
	name: string,
	sources: [string],
	image_url: string,
	created_at: string,
	listened_at: string,
	audio_list: [{
		id: int,
		added_at: string,
	}],
}

export global SlintState {
	in property<[SlintTrack]> index;
	in property<[SlintTrack]> queue;
	in property<[SlintPlaylist]> playlist;
	in property<SlintTimeLine> timeline;
	in property<SlintSettings> settings;
}

export global SettingActions {
	callback new_local_source();
}

export global MediaActions {
	callback media_change(int);
	callback media_start(int);
	callback media_toggle();
	callback media_loop();
	callback media_mix();
	callback add_to_playlist(int, int);

	// Media track
	callback media_change_track_position(int);
	callback media_get_track_position();
	callback media_change_volume(int);
}

export enum MainView { index, playlist, queue, artist, online_source_result }
