export struct SlintTrack {
	id: int,
	title: string,
	artist: string,
	path: string,
	genre: string,
	year: int,
	extension: string,
	file_size: int,
	duration: int,
	playing: bool,
}

export struct SlintQueueItem {
	media_id: int,
}

export struct SlintTimeline {
	current: int,
	length: int,
	str_current: string,
	str_length: string,
}

export struct SlintSettings {
	volume_preset: float
}

export struct SlintPlaylist {
	id: int,
	name: string,
	image_url: string,
	created_at: string,
	listened_at: string,
	sources: [{
		origin: string,
		path: string,
	}],
	tracks: [{
		id: int,
		added_at: string,
	}],
}

export global SlintState {
	in property<[SlintTrack]> index;
	in property<[SlintTrack]> queue;
	in property<[SlintPlaylist]> playlist;
	in property<SlintTimeline> timeline;
	in property<SlintSettings> settings;
	in property<SlintTrack> current_track;
	in property<float> volume;
}

export global SettingActions {
	callback new_local_source();
}

export global MediaActions {
	callback media_change(int);
	callback media_start(int);
	callback media_pause();
	callback media_toggle();
	callback media_loop();
	callback media_mix();
	callback add_to_queue(int);
	callback add_to_playlist(int, int);
	callback get_playing_track() -> SlintTrack;

	callback media_change_track_position(int);
	callback media_get_track_position();
	callback media_change_volume(float);
}

export global ContextMenuActions {
	callback create_new_playlist();
}

export enum MainView { index, playlist, queue, artist, online_source_result }
