import { HorizontalBox, Button, ListView, VerticalBox, StandardTableView, ScrollView } from "std-widgets.slint";
// import { CustomButton } from "custom-elements/custom-button.slint";
import { SlintMediaFile, SlintQueueItem, MediaActions } from "data-flow.slint";
import { Palette } from "style.slint";

export component MainList {
	in property<[SlintMediaFile]> list;

	ScrollView {
		vertical-stretch: 1;
		horizontal-stretch: 1;
		
		for item in list: TouchArea {
			clicked => {
				MediaActions.media_start(item.id);
			}
			
			Rectangle {
				height: 30px;
				background: Palette.secondary-background;
				
				HorizontalBox {
					alignment: start;

					Text { text: item.name; }
					Text { text: item.artist; }
					// Button {
						// 	text: "Play";
						// 	clicked => {
						// 		ma.media_start(item.id);
						// 	}
						// }
				}
			}
		}
	}
}
