import { HorizontalBox, Button, ListView, VerticalBox, StandardTableView, ScrollView } from "std-widgets.slint";
import { SlintMediaFile, SlintQueueItem, MediaActions, SlintPlaylist, MainView } from "data-flow.slint";
import { Palette } from "style.slint";

export component MainList {
	in property<[SlintMediaFile]> list;
	in property<[SlintPlaylist]> playlists;
	property<MainView> main-view-id: MainView.index;

	ScrollView {
		vertical-stretch: 1;
		horizontal-stretch: 1;

		for media in list: TouchArea {
			clicked => {
				MediaActions.media_start(media.id);
			}

			Rectangle {
				height: 30px;
				background: Palette.secondary-background;

				HorizontalBox {
					alignment: start;

					Text { text: media.name; }
					Text { text: media.artist; }
					Text { text: media.playing ? "[1]" : "[0]"; }
					// Button {
						// 	text: "Play";
						// 	clicked => {
						// 		ma.media_start(item.id);
						// 	}
						// }
				}
			}

			ContextMenuArea {
		        Menu {
		            MenuItem {
		                title: @tr("Add to queue");
		                activated => { debug("Add to queue"); }
		            }
		            Menu {
		                title: @tr("Add to playlist");
						// TODO: Dynamically add playlists to context menu. For loop below is not supported.
						// for playlist in playlists: MenuItem {
		                    // title: playlist.name;
							// activated() => { debug("Add to a specific playlist"); }
		                // }
		            }
		        }
		    }
		}
	}
}
