import { HorizontalBox, VerticalBox, Button, Slider } from "std-widgets.slint";
import { MediaActions, SlintState, SlintTimeline } from "data-flow.slint";
import { VolumeSlider } from "components/volume-slider.slint";
import { CurrentlyPlaying } from "components/currently-playing.slint";

export component MediaControllers {
    in-out property <float> volume: SlintState.volume;
    in property <SlintTimeline> playing;
    property <bool> dragging;
    // property <bool> hovering: hover_zone.has-hover;


    Timer {
        property <int> count: 0;
        interval: 1000ms;
        running: SlintState.timeline.length > 0 ? true : false;
        triggered() => {
            if !dragging && playing.current != playing.length {
                MediaActions.media_get_track_position();
            }
        }
    }

    VerticalBox {
    	padding-top: 20px;
     	spacing: 0;

        CurrentlyPlaying {
            track: SlintState.current_track;
        	horizontal-stretch: 1;
        }

        HorizontalBox {
            HorizontalBox {
                spacing: 5px;
                width: 230px;

                HorizontalBox {
	                Button {
						width: 50px;
	                    text: @tr("prev");
	                    clicked => { MediaActions.media_change(-1) }
	                }

	                Button {
						width: 50px;
	                    text: @tr("start");
	                    clicked => { MediaActions.media_toggle() }
	                }

	                Button {
						width: 50px;
	                    text: @tr("next");
	                    clicked => { MediaActions.media_change(1) }
	                }
                }
            }

            HorizontalBox {
            	horizontal-stretch: 1;

	            Text {
	                text: playing.str_current;
	                horizontal-alignment: left;
					vertical-alignment: center;
					width: 30px;
	            }

	            Slider {
	                horizontal-stretch: 1;
	                // width: 300px;
					value: playing.current;
	                minimum: 0.0;
	                maximum: playing.length;
	                changed(_) => {
	                    dragging = true;
	                    MediaActions.media_pause();
	                }
	                released(position) => {
	                    dragging = false;
	                    MediaActions.media_change_track_position(position);
	                    MediaActions.media_toggle();
	                }
	            }

	            Text {
	                text: playing.str_length;
	                horizontal-alignment: right;
					vertical-alignment: center;
					width: 30px;
	            }
            }

            HorizontalBox {
	            spacing: 5px;
            	width: 200px;

	            HorizontalBox {
		            Button {
						width: 50px;
		                text: @tr("mix");
		                clicked => { MediaActions.media_mix() }
		            }

		            Button {
						width: 50px;
		                text: @tr("loop");
		                clicked => { MediaActions.media_loop() }
		            }
	            }

	            volume_slider := Slider {
					// orientation: Orientation.vertical;
	      			// width: hovering ? 100px : 0px;
	                // opacity: hovering ? 1.0 : 0.0;
	                width: 80px;
	                value <=> root.volume;
	                step: 0.1;
	                animate width, opacity { duration: 150ms; }
	                changed(value) => {
	                    MediaActions.media_change_volume(value)
	                }
	            }
			}

    //         hover_zone := TouchArea {
    //             width: 124px;
    //             height: 24px;
				// // Image {
				// // 	width: 24px;
				// // 	height: 24px;
				// // 	source: @image-url("volume-icon.svg");
				// // }
				// HorizontalLayout {
    //                 spacing: 8px;

    //                 Rectangle {
    //                     width: 32px;
    //                     height: 32px;
    //                     background: Colors.red;
    //                 }

    //                 volume_slider := Slider {
				// 		// orientation: Orientation.vertical;
				// 		width: hovering ? 100px : 0px;
    //                     opacity: hovering ? 1.0 : 0.0;
    //                     value <=> root.volume;
    //                     step: 0.1;
    //                     animate width, opacity { duration: 150ms; }
    //                     changed(value) => {
    //                         MediaActions.media_change_volume(value)
    //                     }
    //                 }
    //             }
    //         }
        }
    }
}
