import { ListView, HorizontalBox } from "std-widgets.slint";
import { MediaActions as ma, SlintTrack, SlintState } from "data-flow.slint";
import { Palette } from "style.slint";


export component Queue {
	accessible-role: none;
	accessible-expandable: true;

	in property<[SlintTrack]> queue;

	Text { text: @tr("Queue"); }

	for item in queue: Text {
		text: item.id;
	}

	ListView {
		height: parent.height;

		for item in queue: Rectangle {
			background: pink;
			// height: 30px;

			Text { text: @tr("test text"); }
			TouchArea {
				clicked => {
					ma.media_start(item.id);
				}

				Rectangle {
					height: 30px;
					background: Palette.secondary-background;

					HorizontalBox {
						alignment: start;

						Text { text: item.id; }
						Text { text: item.title; }
					}
				}
			}
		}
	}
}
