import { ListView, HorizontalBox, ScrollView, VerticalBox } from "std-widgets.slint";
import { MediaActions, SlintTrack, SlintState } from "data-flow.slint";
import { Palette } from "style.slint";

export component Queue {
	accessible-role: none;
	accessible-expandable: true;

	in property<[SlintTrack]> queue;

	ScrollView {
		VerticalLayout {
			padding: 5px;
			alignment: start;

			for item in queue: TouchArea {
				clicked => {
					MediaActions.media_start(item.id);
				}

				Rectangle {
					height: 30px;
					background: Palette.secondary-background;

					HorizontalBox {
						alignment: start;
						// spacing: 25px;

						Text {
							horizontal-alignment: left;
							text: item.title + " - " + item.artist;
						}
						Text {
							horizontal-alignment: right;
							text: item.duration;
						}
					}
				}

				ContextMenuArea {
			        Menu {
			            MenuItem {
			                title: @tr("Remove from queue");
			                activated => {
								debug("TODO: Remove logic from queue");
							}
			            }
			        }
			    }
			}
		}
	}
}
