import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { SlintPlaylist } from "data-flow.slint";

component Playlist {
	accessible-role: none;
	accessible-expandable: true;

	in property <SlintPlaylist> data;

	HorizontalBox {
		Image {
			// height: 100%;
			// source: @image-url(data.image_url);
		}

		VerticalBox {
			Text {
				text: data.name;
			}

			Text {
				text: @tr("Source: {}", data.sources.length > 1 
					? @tr("mixed ({})", data.sources.length)
					: data.sources[0]
				);
			}
		}
	}
}

export component SideBar {
	in property <[SlintPlaylist]> list;

	VerticalBox {
		for data in list: Playlist {
			data: data;
			height: 30px;
		}
	}
}
