import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { SlintPlaylist, ContextMenuActions } from "data-flow.slint";

component Playlist {
	accessible-role: none;
	accessible-expandable: true;

	in property <SlintPlaylist> data;

	HorizontalBox {
		// Image {
			// height: 100%;
			// source: @image-url(data.image_url);
		// }

		VerticalBox {
			Text {
				text: data.name;
			}

			Text {
				text: @tr("Source: {}", data.sources.length > 1
					? @tr("mixed ({})", data.sources.length)
					: data.sources[0]
				);
			}
		}
	}
}

export component SideBar {
	in property <[SlintPlaylist]> list;

	VerticalBox {
		Text {
			text: "Placeholder";

			// Context menu needs to be a child of clickable element
			ContextMenuArea {
		        Menu {
		            MenuItem {
		                title: @tr("Create a new playlist");
		                activated => { ContextMenuActions.create_new_playlist(); }
		            }
		        }
		    }
		}

		for data in list: Playlist {
			data: data;
			height: 30px;
		}
	}
}
